<?php
/*
 * Comment the following two lines if you want to display all notices and warnins.
 */
error_reporting(E_ALL);
ini_set('display_errors', 1);

/*
 * Loading the core and application classes using the class loader
 * generated by composer.
 */
require 'vendor/autoload.php';

/*
 * In case you want a pritty way to show errors you can use Whoops library but
 * first you have to plugin the dependencies with composer with the command:
 *     composer require filp/whoops
 */
$whoops = new \Whoops\Run;
$whoops->pushHandler(new \Whoops\Handler\PrettyPageHandler);
$whoops->register();

/*
 * Loading the application and configuration.
 */
require 'core/bootstrap.php';

/*
 * Registering the application's routes from /app/routes.php
 */
\Core\Router::load(__DIR__ . '/app/routes.php')->direct();
